most_recent_recording_path = "F:\\Mobile-Multimodal-Lab\\temp_davide\\MT_freemocap"

[recording_status]
synchronized_videos_status_check = true
data2d_status_check = false
data3d_status_check = false
center_of_mass_data_status_check = false
blender_file_status_check = false
single_video_check = false
calibration_toml_check = false

[recording_status.video_and_camera_info]
number_of_synchronized_videos = 3

[recording_status.video_and_camera_info.number_of_frames_in_videos]
"pilot_06_d2_speech_audiovideo_synced_cam1.mp4" = 5046
"pilot_06_d2_speech_audiovideo_synced_cam2.mp4" = 5046
"pilot_06_d2_speech_audiovideo_synced_cam3.mp4" = 5046
